// Regenerates the vendored Lucide icon assets and the generated Rust enum.
//
//   bun scripts/icons.ts
//
// Pulls the icon font, codepoint map, and license from the `lucide-static`
// npm package (via unpkg) and writes:
//   crates/guise/assets/lucide/lucide.ttf
//   crates/guise/assets/lucide/license.txt
//   crates/guise/src/icon/lucide.rs

const base = "https://unpkg.com/lucide-static@latest"

const fetchAt = async (path: string): Promise<Response> => {
  const res = await fetch(`${base}/${path}`)
  if (!res.ok) throw new Error(`${path}: ${res.status}`)
  return res
}

type IconInfo = { encodedCode: string }

const pkg = (await (await fetchAt("package.json")).json()) as { version: string }
const info = (await (await fetchAt("font/info.json")).json()) as Record<string, IconInfo>
const font = await (await fetchAt("font/lucide.ttf")).arrayBuffer()
const license = await (await fetchAt("LICENSE")).text()

const pascal = (name: string) =>
  name
    .split("-")
    .map((w) => (w ? w[0].toUpperCase() + w.slice(1) : w))
    .join("")

// Some icons ship under two kebab spellings that collapse to the same Pascal
// name (e.g. `arrow-down-0-1` / `arrow-down-01`). They share a codepoint, so
// keep the first and just assert the glyph matches.
const icons: { name: string; variant: string; code: number }[] = []
const byVariant = new Map<string, number>()
for (const name of Object.keys(info).sort()) {
  const code = parseInt(info[name].encodedCode.replace("\\", ""), 16)
  const variant = pascal(name)
  const seen = byVariant.get(variant)
  if (seen !== undefined) {
    if (seen !== code) throw new Error(`variant collision with differing glyphs: ${name}`)
    continue
  }
  byVariant.set(variant, code)
  icons.push({ name, variant, code })
}

const aliases: [string, string][] = [
  ["Close", "X"],
  ["Warning", "TriangleAlert"],
]
for (const [, target] of aliases)
  if (!byVariant.has(target)) throw new Error(`alias target missing: ${target}`)

const chunk = <T>(items: T[], size: number): T[][] =>
  items.reduce<T[][]>((acc, item, i) => {
    if (i % size === 0) acc.push([])
    acc[acc.length - 1].push(item)
    return acc
  }, [])

const table = (items: string[], perLine: number) =>
  chunk(items, perLine)
    .map((line) => `    ${line.join(" ")}`)
    .join("\n")

const rust = `//! Generated by \`bun scripts/icons.ts\` — do not edit by hand.
//!
//! [Lucide](https://lucide.dev) v${pkg.version}, ISC License
//! (see \`assets/lucide/license.txt\`).

/// The bundled Lucide version this table was generated from.
pub const LUCIDE_VERSION: &str = "${pkg.version}";

const COUNT: usize = ${icons.length};

/// A named [Lucide](https://lucide.dev) icon, rendered from the icon font
/// embedded in guise. Every icon in the set is available as a variant.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum IconName {
${icons.map((i) => `    ${i.variant},`).join("\n")}
}

const GLYPHS: [&str; COUNT] = [
${table(icons.map((i) => `"\\u{${i.code.toString(16)}}",`), 8)}
];

const NAMES: [&str; COUNT] = [
${table(icons.map((i) => `"${i.name}",`), 4)}
];

impl IconName {
    /// The private-use codepoint for this icon in the embedded Lucide font.
    pub fn glyph(self) -> &'static str {
        GLYPHS[self as usize]
    }

    /// The upstream kebab-case icon name (as listed on lucide.dev).
    pub fn name(self) -> &'static str {
        NAMES[self as usize]
    }

    /// Every icon in the set, in name order.
    pub fn all() -> &'static [IconName] {
        &ALL
    }
}

const ALL: [IconName; COUNT] = [
${table(icons.map((i) => `IconName::${i.variant},`), 4)}
];

/// Names carried over from the pre-Lucide glyph set.
#[allow(non_upper_case_globals)]
impl IconName {
${aliases.map(([from, to]) => `    pub const ${from}: IconName = IconName::${to};`).join("\n")}
}
`

const root = new URL("..", import.meta.url).pathname
await Bun.write(`${root}crates/guise/assets/lucide/lucide.ttf`, font)
await Bun.write(`${root}crates/guise/assets/lucide/license.txt`, license)
await Bun.write(`${root}crates/guise/src/icon/lucide.rs`, rust)

console.log(`lucide v${pkg.version}: ${icons.length} icons, font ${font.byteLength} bytes`)
