// The landing page. Dark, gradient-washed, component-forward.
//
// The hero carries both halves of what this repository ships, side by side: the
// Tailor workbench on the left, the guise interface it generates on the right.
// Leading with only the library undersold the pair — you cannot tell from a
// component grid that there is a builder for it.
//
// The annotated exhibit (a guise "app" with callouts pointing at the
// components, in the spirit of the React Aria landing page) moved down into the
// components band, where the callouts have the horizontal room they need.

import { shell } from "./shell";
import { ribbon, plate } from "./bits";

const REPO = "https://github.com/wess/guise";
const DEP = 'guise-ui = "1.5"';
const DEP_HTML = DEP.replace(/&/g, "&amp;").replace(/</g, "&lt;");

// A guise interface, in mock. `compact` drops the two rows the hero has no
// vertical room for — the annotated version below shows the whole thing.
function guiseApp(compact = false): string {
  const dimmed = compact ? "" : `<span class="g-dimmed">A component layer for gpui.</span>`;
  const alert = compact
    ? ""
    : `<div class="g-alert"><span class="g-alert-bar"></span><div><strong>Heads up</strong><span class="g-dimmed">Theme switches light / dark at runtime.</span></div></div>`;
  return `<div class="g-app">
  <div class="g-stack">
    <div class="g-row"><span class="g-title">Create project</span><span class="g-badge is-violet">v0.1</span></div>
    ${dimmed}
    <div class="g-field"><span class="g-label">Name</span><div class="g-input"><span>guise-app</span><i class="g-caret"></i></div></div>
    <div class="g-group">
      <button class="g-btn g-btn--filled">Filled</button>
      <button class="g-btn g-btn--light">Light</button>
      <button class="g-btn g-btn--outline">Outline</button>
    </div>
    <div class="g-group g-badges">
      <span class="g-badge is-blue">Blue</span>
      <span class="g-badge is-teal">Teal</span>
      <span class="g-badge is-grape">Grape</span>
      <span class="g-badge is-orange">Orange</span>
    </div>
    <div class="g-switchrow"><span class="g-switch is-on"><i></i></span><span class="g-dimmed">Enable notifications</span></div>
    ${alert}
    <div class="g-progress"><span style="width:68%"></span></div>
  </div>
</div>`;
}

// The annotated exhibit: the same interface with callout labels naming the
// components it is made of.
function exhibit(): string {
  const app = guiseApp();
  const cal = (cls: string, top: string, label: string) =>
    `<span class="cal ${cls}" style="top:${top}"><span>${label}</span></span>`;
  return `<div class="exhibit">
  <div class="exhibit-wash" aria-hidden="true"></div>
  <div class="winwrap">
    <div class="win" role="img" aria-label="A guise interface: a title, an input, buttons, badges, a switch, an alert and a progress bar.">
      <div class="win-bar"><span class="win-dots"><i></i><i></i><i></i></span><span class="win-title">guise · gallery</span></div>
      <div class="win-body">${app}</div>
    </div>
    ${cal("cal-l", "31%", "TextInput")}
    ${cal("cal-r", "46%", "Button · variant")}
    ${cal("cal-l", "60%", "Badge")}
    ${cal("cal-r", "73%", "Switch")}
    ${cal("cal-l", "85%", "Alert")}
  </div>
</div>`;
}

const SAMPLE_CODE = `<span class="t-c">// a stateful entity: owns its buffer, emits events</span>
<span class="t-k">let</span> name = cx.new(|cx| {
    <span class="t-t">TextInput</span>::new(cx)
        .label(<span class="t-s">"Name"</span>)
        .placeholder(<span class="t-s">"guise-app"</span>)
});

cx.subscribe(&name, |this, _input, e: &<span class="t-t">TextInputEvent</span>, cx| {
    <span class="t-k">if let</span> <span class="t-t">TextInputEvent</span>::Change(value) = e {
        this.name = value.clone();
        cx.notify();
    }
})
.detach();`;

// Lifted verbatim from `generate_code` on the dashboard template — the point of
// the band is that this is what actually falls out, so it should not be prose.
const TAILOR_CODE = `<span class="t-c">//! DashboardScreen — generated by Tailor from Dashboard.</span>
<span class="t-c">//! …take this file and own it; it has no dependency on Tailor.</span>

<span class="t-k">use</span> gpui::prelude::*;
<span class="t-k">use</span> guise::prelude::*;
<span class="t-k">use</span> super::<span class="t-t">StatCard</span>;

<span class="t-k">impl</span> <span class="t-t">Render</span> <span class="t-k">for</span> <span class="t-t">DashboardScreen</span> {
    <span class="t-k">fn</span> render(&amp;<span class="t-k">mut</span> self, …) -&gt; <span class="t-k">impl</span> <span class="t-t">IntoElement</span> {
        <span class="t-t">AppShell</span>::new()
            .child(
                div()
                    .flex()
                    .flex_col()
                    .gap(px(<span class="t-s">20.</span>))
                    .p(px(<span class="t-s">24.</span>))
                    .child(
                        div()
                            .flex_row()
                            .gap(px(<span class="t-s">16.</span>))
                            .child(<span class="t-t">StatCard</span>::new())
                            .child(<span class="t-t">StatCard</span>::new())
                    )
            )
    }
}`;

// A sketch of the workbench: library rail, canvas, inspector.
function tailorMock(): string {
  const rail = (n: number, on: number) =>
    Array.from({ length: n }, (_, i) => `<i${i === on ? ' class="is-on"' : ""}></i>`).join("");
  return `<div class="win tailor-win" role="img" aria-label="The Tailor workbench: a component library on the left, a canvas of cards in the middle, an inspector on the right.">
  <div class="win-bar"><span class="win-dots"><i></i><i></i><i></i></span><span class="win-title">Tailor · DashboardScreen</span></div>
  <div class="tailor-body">
    <div class="tailor-rail">${rail(7, 2)}</div>
    <div class="tailor-canvas">
      <div class="tailor-cards"><span class="tailor-card"></span><span class="tailor-card is-sel"></span><span class="tailor-card"></span></div>
      <span class="tailor-chart"></span>
    </div>
    <div class="tailor-insp">${rail(6, 0)}</div>
  </div>
</div>`;
}

// The hero exhibit: the two things this repository ships, and the arrow
// between them. The builder on the left is not a preview of the app on the
// right — it renders the same components, which is the whole claim.
function heroDuo(): string {
  return `<div class="hero-duo">
  <figure class="duo duo--tailor">
    <figcaption class="duo-cap"><span class="duo-k">Tailor</span> the builder</figcaption>
    ${tailorMock()}
    <p class="duo-note">Drag real components onto a canvas, wire the state and the actions, and export.</p>
  </figure>
  <span class="duo-join" aria-hidden="true"><i></i><em>generates</em><i></i></span>
  <figure class="duo duo--guise">
    <figcaption class="duo-cap"><span class="duo-k">guise</span> the components</figcaption>
    <div class="win" role="img" aria-label="A guise interface: a title, an input, buttons, badges, a switch and a progress bar.">
      <div class="win-bar"><span class="win-dots"><i></i><i></i><i></i></span><span class="win-title">people.rs</span></div>
      <div class="win-body">${guiseApp(true)}</div>
    </div>
    <p class="duo-note">Rust you own, with no dependency on Tailor left in it — or write it by hand from the start.</p>
  </figure>
</div>`;
}

type Feature = { icon: string; title: string; body: string };
const features: Feature[] = [
  { icon: "&#9632;", title: "Themed palette", body: "A 14-hue open-color palette, sizing tokens, and semantic colors. Read every value from the theme — light / dark switching is free." },
  { icon: "&#8943;", title: "Builder API", body: "Chainable builders that read the same on every component: <code>.variant()</code>, <code>.color()</code>, <code>.size()</code>, <code>.radius()</code>." },
  { icon: "&#9651;", title: "Stateful entities", body: "Inputs, overlays and data views are gpui entities that own their state and emit events you take with <code>cx.subscribe</code>." },
  { icon: "&#9707;", title: "Flex + macros", body: "A Flutter-style flexbox layer plus terse <code>row!</code> / <code>col!</code> / <code>zstack!</code> macros for dense layout." },
  { icon: "&#10022;", title: "Reactive state", body: "A lightweight React-style layer: <code>Signal</code>, <code>use_state</code>, <code>provide</code> / <code>use_context</code>, and <code>use_form</code> validation." },
  { icon: "&#9673;", title: "Native WebView", body: "Embed a real OS web view (WKWebView / WebView2 / WebKitGTK) via <code>wry</code>, positioned inside normal guise layout." },
  { icon: "&#10038;", title: "Lucide icons built in", body: "Every <a href=\"https://lucide.dev\">Lucide</a> icon as an <code>IconName</code> variant, drawn from an embedded icon font — no asset pipeline, tinted and sized like text." },
  { icon: "&#9707;&#65038;", title: "An inspector in the box", body: "<a href=\"devtools.html\">DevTools</a> shaped like Safari's Web Inspector — an element tree your components record themselves, the box model, resolved styles with the line each came from, plus logs, network and timelines the host feeds." },
  { icon: "&#8635;", title: "Self-update included", body: "<a href=\"update.html\">Check a release feed</a>, install the new version in place — rsync onto the <code>.app</code>, rename over the AppImage — verify its signature, and restart. Prompt included." },
  { icon: "&#9998;", title: "A builder in the box", body: "<a href=\"https://github.com/wess/tailor\" rel=\"noreferrer\">Tailor</a> lays these components out on a canvas and writes the Rust — a drag-and-drop interface builder that draws with the real components." },
  { icon: "&#9993;", title: "An AI chat kit", body: "<a href=\"ai.html\">Transcript, composer, streaming text, reasoning blocks, tool calls, citations and a cost meter</a> — transport-agnostic, so nothing here opens a socket or holds a key." },
  { icon: "&#9636;", title: "Data views that scale", body: "<a href=\"data.html\"><code>TableView</code>, <code>DataView</code>, <code>TreeView</code></a> and <code>VirtualList</code> window their rows — a hundred thousand of them render as cheaply as twenty." },
];

function bandHead(h: string, p: string, learnHref?: string, learnLabel?: string): string {
  const learn = learnHref ? `<a class="learn" href="${learnHref}">${learnLabel} &#8594;</a>` : "";
  return `<div class="band-head"><h2>${h}</h2><p>${p}</p>${learn}</div>`;
}

export function renderLanding(): string {
  const featureCards = features
    .map((f) => `<article class="feature"><span class="ic">${f.icon}</span><h3>${f.title}</h3><p>${f.body}</p></article>`)
    .join("");

  const teaser = [
    plate({ index: "01", name: "Button", note: "variant · color · size", href: "buttons.html", preview: `<div class="g-group"><button class="g-btn g-btn--filled">Filled</button><button class="g-btn g-btn--light">Light</button><button class="g-btn g-btn--outline">Outline</button></div>` }),
    plate({ index: "02", name: "Inputs", note: "TextInput · Select", href: "inputs.html", preview: `<div class="g-col"><div class="g-field"><span class="g-label">Email</span><div class="g-input"><span>you@studio.dev</span></div></div><div class="g-field"><span class="g-label">Framework</span><div class="g-select"><span>gpui</span><i class="g-chev"></i></div></div></div>` }),
    plate({ index: "03", name: "Controls", note: "Switch · Checkbox · Slider", href: "inputs.html", preview: `<div class="g-col g-col--gap"><div class="g-switchrow"><span class="g-switch is-on"><i></i></span><span class="g-dimmed">Sync</span></div><div class="g-checkrow"><span class="g-check is-on">&#10003;</span><span class="g-dimmed">I agree</span></div><div class="g-slider"><span class="g-slider-fill" style="width:55%"></span><span class="g-slider-knob" style="left:55%"></span></div></div>` }),
    plate({ index: "04", name: "Feedback", note: "Alert · Progress · Loader", href: "feedback.html", preview: `<div class="g-col g-col--gap"><div class="g-alert"><span class="g-alert-bar is-teal"></span><div><strong>Saved</strong><span class="g-dimmed">All changes synced.</span></div></div><div class="g-progress"><span style="width:42%"></span></div><div class="g-group"><span class="g-ring"></span><span class="g-loader"></span></div></div>` }),
    plate({ index: "05", name: "Data", note: "Tabs · AvatarGroup", href: "data.html", preview: `<div class="g-col"><div class="g-tabs"><span class="is-on">Overview</span><span>Activity</span><span>Members</span></div><div class="g-avatars"><i class="is-blue">WC</i><i class="is-grape">AD</i><i class="is-teal">JR</i><i class="more">+3</i></div></div>` }),
    plate({ index: "06", name: "Overlays", note: "Menu · Popover · Modal", href: "overlays.html", preview: `<div class="g-menu"><span class="g-menu-h">Actions</span><span class="g-menu-i">Duplicate</span><span class="g-menu-i is-on">Rename</span><span class="g-menu-i is-danger">Delete</span></div>` }),
  ].join("");

  const systems = [
    ["Flex layout", "Row · Column · Expanded · Wrap", "flex.html"],
    ["Macros", "row! · col! · style! · motion!", "macros.html"],
    ["Reactive state", "Signal · use_state · use_form", "reactive.html"],
    ["Motion", "Motion · Sequence · Stagger · Animator", "transitions.html"],
    ["Theming", "14 hues × 10 shades · light / dark", "theming.html"],
    ["Native WebView", "WKWebView · WebView2 · WebKitGTK", "webview.html"],
    ["Drag &amp; drop", "Draggable · DropTarget · SortableList", "dnd.html"],
    ["DevTools", "Elements · Styles · Logs · Audit", "devtools.html"],
    ["Software update", "check · verify · install in place", "update.html"],
  ]
    .map(
      ([t, n, h], i) =>
        `<a class="sysrow" href="${h}"><span class="sys-n">${String(i + 1).padStart(2, "0")}</span><span class="sys-t">${t}</span><span class="sys-d">${n}</span><span class="sys-x">&#8594;</span></a>`,
    )
    .join("");

  const endCards = [
    ["Install &amp; setup", "Add the dependency, install a theme, render your first window.", "gettingstarted.html"],
    ["Browse components", "Every component family on one palette, in the gallery.", "gallery.html"],
    ["Read the docs", "Theming, the component model, layout, reactive state and more.", "docs.html"],
  ]
    .map(([t, d, h]) => `<a class="endcard" href="${h}"><h3>${t} &#8594;</h3><p>${d}</p></a>`)
    .join("");

  const body = `
<section class="hero">
  <div class="container">
    <span class="eyebrow">Native UI · built on Zed's gpui</span>
    <h1 class="display display--wide">Native UI for Rust.<br /><span class="grad">Write it, or draw it.</span></h1>
    <p class="lead">
      <strong>guise</strong> is a batteries-included component layer for
      <a href="https://github.com/zed-industries/zed" rel="noreferrer">gpui</a> — a themed palette,
      sizing tokens, and over a hundred and thirty composable components, GPU-rendered at native speed.
      <strong>Tailor</strong> is the drag-and-drop builder for it, in the same repository: it lays those
      same components out on a canvas and hands back the Rust.
    </p>
    <div class="hero-cta">
      <a class="btn btn-primary" href="gettingstarted.html">Get started</a>
      <a class="btn btn-ghost" href="https://github.com/wess/tailor" rel="noreferrer">Meet Tailor</a>
      <a class="btn btn-ghost" href="gallery.html">Explore components</a>
    </div>
    <div class="cmd" style="margin-left:auto;margin-right:auto;">
      <code>${DEP_HTML}</code>
      <button class="copybtn" data-copy='${DEP}' aria-label="Copy dependency line">Copy</button>
    </div>
    ${heroDuo()}
    ${ribbon(true)}
    <p class="ribbon-cap">The palette — 14 open-color hues, 10 shades each, read straight from the theme.</p>
  </div>
</section>

<section class="band band-violet">
  <div class="container">
    ${bandHead(`Everything you need to <span class="gw">build a desktop app</span>.`, "A complete component layer, not a widget grab-bag — themed, composable, and native from the first line.")}
    <div class="feature-grid">${featureCards}</div>
  </div>
</section>

<section class="band band-blue">
  <div class="container">
    ${bandHead(`Two patterns, and you know the whole <span class="gw">library</span>.`, "Controlled widgets take a value and a handler. Stateful ones are entities you create with cx.new and subscribe to. Same mental model — native rendering underneath.", "components.html", "Read the component model")}
    <div class="split">
      <div class="split-copy">
        <ul class="ticks">
          <li>Variant + color + size on every component</li>
          <li>Events via <code>cx.subscribe</code>, redraws via <code>cx.notify</code></li>
          <li>No hardcoded colors or spacing — only theme tokens</li>
          <li>Drop to the flex layer or macros when you want them</li>
        </ul>
      </div>
      <div class="codepanel">
        <div class="codepanel-bar"><i></i><i></i><i></i><span>text.rs</span></div>
        <pre class="code"><code>${SAMPLE_CODE}</code></pre>
      </div>
    </div>
  </div>
</section>

<section class="band band-grape">
  <div class="container">
    ${bandHead(`Over 130 components, <span class="gw">one palette</span>.`, "From buttons to a native web view, a code editor and an AI chat kit — a selection of the families below.")}
    ${exhibit()}
    <p class="ribbon-cap">One window, seven components, every value read from the theme.</p>
    <div class="plate-grid">${teaser}</div>
    <a class="more-link" href="gallery.html">See every component in the gallery &#8594;</a>
  </div>
</section>

<section class="band band-teal">
  <div class="container">
    ${bandHead(`Systems, not just <span class="gw">widgets</span>.`, "Layout, motion and state — the parts of an app a component grab-bag leaves out.")}
    <div class="syslist">${systems}</div>
    <a class="more-link" href="tutorial.html">See them all in one app — the data workbench tutorial &#8594;</a>
  </div>
</section>

<section class="band band-orange">
  <div class="container">
    ${bandHead(`Draw the interface. <span class="gw">Keep the Rust</span>.`, "Tailor is a drag-and-drop builder for guise, downloadable as an app. Its canvas renders the real components against the real theme — there is no second drawing to keep in step — so what you lay out is what it generates, and what it generates is a file you own.", "https://github.com/wess/tailor", "Read about Tailor")}
    <div class="split">
      ${tailorMock()}
      <div class="codepanel">
        <div class="codepanel-bar"><i></i><i></i><i></i><span>dashboard_screen.rs</span></div>
        <pre class="code"><code>${TAILOR_CODE}</code></pre>
      </div>
    </div>
    <ul class="ticks ticks-wide">
      <li>101 components in the library rail, an Interface-Builder five-tab inspector, and a Problems panel</li>
      <li>A <code>Render</code> entity when the screen holds state, a <code>RenderOnce</code> builder when it does not</li>
      <li>State variables become <code>Signal</code> fields; events become <code>cx.listener</code> and <code>cx.subscribe</code></li>
      <li>Eight resize knobs, snapping to grid and to siblings, and a live window that follows every edit</li>
      <li>An MCP server over the same document, so an agent can build a screen while you watch the canvas</li>
      <li>Jumps both ways with your editor — a component to its generated line, and a line back to its component</li>
    </ul>
    <div class="endgrid endgrid--tailor">
      <a class="endcard" href="https://github.com/wess/tailor/blob/main/docs/tutorial.md" rel="noreferrer"><h3>Tailor tutorial &#8594;</h3><p>Build an app end to end in the builder, export it, and run what comes out.</p></a>
      <a class="endcard" href="https://github.com/wess/tailor/blob/main/docs/codegen.md" rel="noreferrer"><h3>What it generates &#8594;</h3><p>The shape of the output, the two flavours, and the <code>.tailor</code> file format.</p></a>
      <a class="endcard" href="${REPO}/releases" rel="noreferrer"><h3>Download Tailor &#8594;</h3><p>Every release attaches <code>Tailor.dmg</code>, signed and built from this repository.</p></a>
    </div>
  </div>
</section>

<section class="band band-pink">
  <div class="container">
    ${bandHead(`Ready to <span class="gw">get started</span>?`, "Add the dependency and open your first window.")}
    <div class="cmd"><code>${DEP_HTML}</code><button class="copybtn" data-copy='${DEP}' aria-label="Copy dependency line">Copy</button></div>
    <div class="endgrid">${endCards}</div>
  </div>
</section>`;

  return shell({
    title: "guise — native UI components for Rust, and Tailor, the builder for them",
    description:
      "A component library for gpui (Zed's GPU UI framework): themed palette, sizing tokens, and 130+ composable, GPU-rendered components for native Rust desktop apps — plus Tailor, the drag-and-drop interface builder that generates them.",
    body,
    active: "home",
  });
}
